###############################################################################
#     本项目的源代码在MPL2.0协议下发布，同时附加以下条目：                          #
#        非商业性使用 — 不得将此项目用于任何商业和盈利用途                          #
###############################################################################
users:
  - user:
    username: "Eyvind" # 备注信息
    #code: "" # 智慧川信code
    Cookie: "X_CACHE_KEY=edd11e6d708f876670357d80d369e887; PHPSESSID=3k3u4fkhu3420f47ju9tdse23n"
    Temperature: "" # 体温
    InSchool: "在校"
    GoOutYN: "在广元"
    #lat: latitudesj # 维度
    #lon: longitudesj # 经度
    qq_gid: "1834505843" # 推送的qq群号
